### ISSUE TITLE
[ERROR] Failed to execute goal com.github.cjnygard:rest-maven-plugin:0.1.4:rest-request (default-cli) on project ConfigOnly: Execution default-cli of goal com.github.cjnygard:rest-maven-plugin:0.1.4:rest-request failed: URI of the newly created target must not be null.

### ISSUE THREAD

**Issue by sharadpatil2018** [cjnygard/rest-maven-plugin#7]
What could be reason for this error:  ``` 
           <plugin>
                <groupId>com.github.cjnygard</groupId>
                <artifactId>rest-maven-plugin</artifactId>
                <version>0.1.4</version>
                <executions>
                    <execution>
                        <id>create-keystore</id>
                        <phase>prepare-classes</phase>
                        <goals>
                            <goal>rest-request</goal>
                        </goals>
                        <configuration>
                            <endpoint>https://api.enterprise.apigee.com/v1</endpoint>
                            <resource>/organizations/demo-dev/environments/develop/keystores</resource>
                            <fileset>
                                <directory>${project.build.resourcepath}</directory>
                                <includes>
                                    <include>*.json</include>
                                </includes>
                            </fileset>
                            <requestType>
                                <type>application</type>
                                <subtype>json</subtype>
                            </requestType>
                            <responseType>
                                <type>application</type>
                                <subtype>json</subtype>
                            </responseType>
                            <headers>
                                <Content-Type>application/json</Content-Type>
                            </headers>
                            <outputDir>target/out/json</outputDir>
                        </configuration>
                    </execution>
                </executions>
            </plugin> ```

**Comment by cjnygard** [comment]
I suspect that you're invoking the plugin from the maven command line, rather than as part of a normal build lifecycle?  If so, you should check out the docs: https://maven.apache.org/guides/mini/guide-default-execution-ids.html

You only define an execution, and have no plugin-level configuration, so in the absence of an execution with an id of `default-cli`, I believe you'll get a plugin that has no configuration.

Please close the issue if your configuration is in error.  Otherwise, I'd need more info on how you're invoking this to investigate any further.

**Comment by cjnygard** [comment]
Closing issue
